### ISSUE TITLE
Improve UX for auto-upgrading

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/desktop#53]
After a new version was automatically downloaded in the background:

- [x] Add a menu item to trigger an explicit & immediate check for a new version
  → #62
- [x] Change the Tray icon to notify the user about a pending upgrade. An example from Docker Desktop: 
   <img width="38" alt="Screenshot 2022-08-09 at 15 42 30" src="https://user-images.githubusercontent.com/1140553/183700918-9d960f37-cc39-4173-a220-c1888de8b43d.png"> <img width="42" alt="Screenshot 2022-08-09 at 15 45 00" src="https://user-images.githubusercontent.com/1140553/183700925-60c47eaa-46a0-4d86-95f6-badecd0991d2.png">
  → https://github.com/filecoin-project/filecoin-station/issues/166
- [x] Remove OS-level notifications about a new version being available

Out of scope:

- Show a banner at the top of the window to let the user know about the new version and ask them to restart the app to upgrade. Or a button in the top window bar. 
  → https://github.com/filecoin-project/filecoin-station/issues/137
- Auto-restart app the app when it's running in the tray (but not when it's open)

**Comment by bajtos** [comment]
See https://github.com/ipfs/ipfs-desktop/pull/841/files and the latest version in https://github.com/ipfs/ipfs-desktop/blob/main/src/auto-updater/index.js

**Comment by juliangruber** [comment]
> * After a new version was automatically downloaded in background, show a banner at the top of the window to let the user know about the new version and ask them to restart the app to upgrade.

We could also use desktop notifications for this, so that we can iterate without UI needs. This will also show it if the app is minimized / hidden in the menu bar.

If we want people to always update timely, then I think adding this proposed banner, and even changing the application icon in the menu bar (add red exclamation mark or so) will help enforce an upgrade.

If we want to be even more enforcing, we could automatically restart the app for them. If they have the window currently visible, we could show a dialog "will be restarted in ...". I wonder how important timely updates are for us?

**Comment by bajtos** [comment]
I prefer to avoid obtrusive notifications as much as possible. IMO, we should gently nudge our users to update soon, but not push them.

I like the idea of changing the application icon (the tray icon) 👍🏻

**Comment by bajtos** [comment]
> I prefer to avoid obtrusive notifications as much as possible. IMO, we should gently nudge our users to update soon, but not push them.

FWIW, the current implementation is already showing OS-level notification 😞 
https://github.com/filecoin-project/filecoin-station/blob/dcd883bdae4f8a3d3b60a685c5b92e9d08d84c54/main/updater.js#L41-L48
