### ISSUE TITLE
Handle keychain access delays and errors

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/desktop#609]
When Filecoin Desktop starts on macOS, the user is prompted to allow access to `filecoin-station-wallet" stored in the keychain.

<img width="546" alt="Screenshot 2023-03-29 at 11 49 48" src="https://user-images.githubusercontent.com/1140553/228496560-2640981f-e99e-432f-ac55-48015e44ea6e.png">

## 1. Error path

The user denies access. Station reports an unknown error.

<img width="328" alt="Screenshot 2023-03-29 at 11 50 07" src="https://user-images.githubusercontent.com/1140553/228496649-edab22c9-c917-416b-9047-58ded3de4391.png">

Station starts, the tray icon reports offline mode.

Activity log mentions this error too.

<img width="784" alt="Screenshot 2023-03-29 at 11 51 26" src="https://user-images.githubusercontent.com/1140553/228496872-2d8e4eb2-3073-495c-bc60-0897dff9dfca.png">

**I find this confusing from the perspective of a non-technical user. What is the error trying to tell me and how can I fix the problem?**

## 2. Happy path with delay

Restarting the Station, granting it a one-time access to the item stored in my keychain. Station happily starts now.

When I open the Wallet UI, I don't see any wallet address 😱

<img width="218" alt="Screenshot 2023-03-29 at 11 53 39" src="https://user-images.githubusercontent.com/1140553/228497518-7350dfce-c047-4284-b11f-7efa55d94a04.png">

The button "Copy" places an empty string to the clipboard.

Opening and closing the window does not fix the issue. (Should we start closing the browser window instead of hiding it?)

Restarting the Station does not help either, because the keychain prompt is shown again.

The only solution I found is to force reload of the UI using the shortcut I know from my browser: <kbd>Command</kbd>+<kbd>R</kbd>

**Comment by bajtos** [comment]
How to revoke "Always Allow" access granted in the past:

1. Open the app Keychain Access
2. In the default keychain “login”, find filecoin-station-wallet§
3. Right-click, choose “Get info”
4. Switch to the second tab called “Access control”
5. Remove the apps, then “Save changes”

<img width="1071" alt="Screenshot 2023-03-29 at 11 39 13" src="https://user-images.githubusercontent.com/1140553/228499396-28dec8ea-4f8a-46d0-a148-b473c305e569.png">

**Comment by taesuklee** [comment]
The empty string in the UI happens when the [setWalletBalance](https://github.com/filecoin-station/desktop/blob/main/renderer/src/hooks/StationWallet.tsx#L87) function in the StationWallet component is called before the wallet address in [wallet-backend](https://github.com/filecoin-station/desktop/blob/main/main/wallet-backend.js#L47) gets set. 
This is why the wallet address is also empty if the user does not type in the password for the keychain "fast enough", meaning this issue could occur in other occations. The solutions I can think of are

1.  Simply passing the isOpen as prop to [useWallet](https://github.com/filecoin-station/desktop/blob/main/renderer/src/hooks/StationWallet.tsx#L29).
- The component is rerendered every time isOpen state changes.
2. Listen on the station address change event.
